### ISSUE TITLE
Set Up SQL Database Integration for Github Data

### ISSUE THREAD

**Issue by mario99logic** [eyalFischel/maakaf-stats#18]
Set up PostgreSQL tables according to the specified schema.
expected a fully functional database setup that can store GitHub data effectively.

**Comment by eyalFischel** [comment]
Are you done? @mario99logic  If so please close the ticket.

**Comment by mario99logic** [comment]
The PostgreSQL database setup has been completed and is fully functional. Closing this issue now.
