### ISSUE TITLE
Lint and formatting 

### ISSUE THREAD

**Issue by eyalFischel** [eyalFischel/maakaf-stats#32]
Your code is not linted and formatted. Please fix it with Black and pylint. Feel free to use the [Makefile](https://github.com/eyalFischel/maakaf-stats/blob/main/Makefile) to manage linting and tests.

Failed run: [GitHub Actions](https://github.com/eyalFischel/maakaf-stats/actions/runs/9628227831/job/26556239809)

(Screaming for now for all the repos, I will change it to the PR after fixing and closing this issue)

**Comment by Avev** [comment]
On it, I'll make a PR after I finish with the discord bot
