### ISSUE TITLE
Design the Postgres DB 

### ISSUE THREAD

**Issue by eyalFischel** [eyalFischel/maakaf-stats#9]
Before implementation and creation, we need to design our database tables. 
Please share your thoughts and designs using draw.io.
@Avev 
@mario99logic

**Comment by mario99logic** [comment]
First step Im thinking of making a user class and make discord user linkedIn user and a Github user all inherited from the user class.
That way we add the necessary classes to and connect them with the correct User type.
<img width="682" alt="Screenshot 2024-06-05 at 19 05 48" src="https://github.com/eyalFischel/maakaf-stats/assets/104531719/ec0f712c-b0ef-4fc0-939d-887b8fc615eb">

**Comment by eyalFischel** [comment]
@mario99logic Add repo ID , connect the tables by User ID and repo ID
